sudo: required
dist: trusty

language: haxe

#os:
#  - linux
#  - osx
  
haxe:
  - "3.2.1"
  - development
#  
#matrix:
#  allow_failures:
#    - haxe: development
    
install:
  - haxelib install tink_runloop --always
  - haxelib install tink_tcp --always
  - haxelib install travix --always
  - haxelib run travix install

script:
  # Test all quite clients
  - haxe test.hxml -D containers=node -D targets=php,node,neko

  # Test servers
  - haxe test.hxml -D containers=php -D targets=neko
  - haxe test.hxml -D containers=node -D targets=node
  - haxe test.hxml -D containers=neko-tools -D targets=neko
  - haxe test.hxml -D containers=neko-mod -D targets=neko
  - haxe test.hxml -D containers=neko -D targets=neko
  - haxe test.hxml -D containers=java -D targets=java
  - haxe test.hxml -D containers=cpp -D targets=cpp
